# Generated by Django 6.0.6 on 2026-07-21 14:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(help_text="Neighborhood/area this fee applies to, e.g. 'Wuse II', 'Karu'", max_length=100, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Delivery fee for this area', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('temporary', 'Temporarily Unavailable')], db_index=True, default='active', help_text='Current availability of this zone', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['area_name'],
                'indexes': [models.Index(fields=['area_name'], name='delivery_de_area_na_ba55f0_idx'), models.Index(fields=['status'], name='delivery_de_status_fc3e37_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week')),
                ('time_slot_name', models.CharField(help_text="e.g., 'Morning', 'Afternoon', 'Evening'", max_length=50)),
                ('start_time', models.TimeField(help_text='Slot start time')),
                ('end_time', models.TimeField(help_text='Slot end time')),
                ('max_orders_per_slot', models.PositiveIntegerField(default=10, help_text='Maximum orders per time slot')),
                ('current_orders', models.PositiveIntegerField(default=0, help_text='Current number of orders for this slot')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this time slot is available')),
                ('zone', models.ForeignKey(help_text='Zone this schedule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='delivery.deliveryzone')),
            ],
            options={
                'verbose_name': 'Delivery Schedule',
                'verbose_name_plural': 'Delivery Schedules',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('zone', 'day_of_week', 'time_slot_name')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of exception')),
                ('exception_type', models.CharField(choices=[('holiday', 'Public Holiday'), ('closure', 'Temporary Closure'), ('weather', 'Weather Issue'), ('event', 'Special Event'), ('maintenance', 'System Maintenance')], help_text='Type of exception', max_length=20)),
                ('title', models.CharField(help_text="Short title (e.g., 'Christmas Day')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('delivery_available', models.BooleanField(default=False, help_text='Is delivery available on this date?')),
                ('modified_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Modified delivery fee for this date', max_digits=10, null=True)),
                ('modified_schedule', models.CharField(blank=True, help_text="Modified schedule (e.g., '10am-2pm only')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zones', models.ManyToManyField(blank=True, help_text='Affected zones (leave empty for all zones)', related_name='exceptions', to='delivery.deliveryzone')),
            ],
            options={
                'verbose_name': 'Delivery Exception',
                'verbose_name_plural': 'Delivery Exceptions',
                'ordering': ['date'],
                'unique_together': {('date', 'title')},
            },
        ),
    ]
