# Generated by Django 6.0.2 on 2026-02-14 07:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Zone name (e.g., 'Zone A - Jahi', 'Zone B - Wuse')", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short code for the zone (e.g., 'JAH', 'WUS', 'MAI')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of areas covered by this zone')),
                ('areas', models.TextField(help_text='List of areas/neighborhoods in this zone, separated by commas')),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base delivery fee for this zone', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order amount for free delivery (null = no free delivery)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_delivery_days', models.PositiveIntegerField(default=1, help_text='Estimated delivery days for this zone', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('rush_delivery_available', models.BooleanField(default=False, help_text='Whether rush/same-day delivery is available for this zone')),
                ('rush_delivery_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional fee for rush delivery', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('temporary', 'Temporarily Unavailable')], db_index=True, default='active', help_text='Current availability of this zone', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order to display zones in dropdowns')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='delivery_de_code_325837_idx'), models.Index(fields=['status'], name='delivery_de_status_fc3e37_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name', max_length=100)),
                ('rule_type', models.CharField(choices=[('distance', 'Distance-based'), ('weight', 'Weight-based'), ('special', 'Special Event'), ('promotion', 'Promotional')], db_index=True, help_text='Type of pricing rule', max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum value (distance in km, weight in kg, etc.)', max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value', max_digits=10, null=True)),
                ('fee_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Order'), ('per_unit', 'Per Unit (km/kg)')], default='fixed', help_text='How to calculate the fee', max_length=20)),
                ('fee_value', models.DecimalField(decimal_places=2, help_text='Fee amount, percentage, or rate per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applies_to_rush', models.BooleanField(default=True, help_text='Whether this rule applies to rush deliveries')),
                ('applies_to_regular', models.BooleanField(default=True, help_text='Whether this rule applies to regular deliveries')),
                ('valid_from', models.DateTimeField(blank=True, help_text='Rule valid from this date', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Rule valid until this date', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(blank=True, help_text='Apply to specific zone (null = all zones)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='delivery.deliveryzone')),
            ],
            options={
                'verbose_name': 'Delivery Pricing Rule',
                'verbose_name_plural': 'Delivery Pricing Rules',
                'ordering': ['rule_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of week')),
                ('time_slot_name', models.CharField(help_text="e.g., 'Morning', 'Afternoon', 'Evening'", max_length=50)),
                ('start_time', models.TimeField(help_text='Slot start time')),
                ('end_time', models.TimeField(help_text='Slot end time')),
                ('max_orders_per_slot', models.PositiveIntegerField(default=10, help_text='Maximum orders per time slot')),
                ('current_orders', models.PositiveIntegerField(default=0, help_text='Current number of orders for this slot')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this time slot is available')),
                ('zone', models.ForeignKey(help_text='Zone this schedule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='delivery.deliveryzone')),
            ],
            options={
                'verbose_name': 'Delivery Schedule',
                'verbose_name_plural': 'Delivery Schedules',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('zone', 'day_of_week', 'time_slot_name')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of exception')),
                ('exception_type', models.CharField(choices=[('holiday', 'Public Holiday'), ('closure', 'Temporary Closure'), ('weather', 'Weather Issue'), ('event', 'Special Event'), ('maintenance', 'System Maintenance')], help_text='Type of exception', max_length=20)),
                ('title', models.CharField(help_text="Short title (e.g., 'Christmas Day')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('delivery_available', models.BooleanField(default=False, help_text='Is delivery available on this date?')),
                ('modified_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Modified delivery fee for this date', max_digits=10, null=True)),
                ('modified_schedule', models.CharField(blank=True, help_text="Modified schedule (e.g., '10am-2pm only')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zones', models.ManyToManyField(blank=True, help_text='Affected zones (leave empty for all zones)', related_name='exceptions', to='delivery.deliveryzone')),
            ],
            options={
                'verbose_name': 'Delivery Exception',
                'verbose_name_plural': 'Delivery Exceptions',
                'ordering': ['date'],
                'unique_together': {('date', 'title')},
            },
        ),
    ]
