# Generated by Django 6.0.6 on 2026-07-09 04:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypricingrule',
            name='zone',
        ),
        migrations.AlterModelOptions(
            name='deliveryzone',
            options={'ordering': ['state'], 'verbose_name': 'Delivery Zone', 'verbose_name_plural': 'Delivery Zones'},
        ),
        migrations.RemoveIndex(
            model_name='deliveryzone',
            name='delivery_de_code_325837_idx',
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Delivery fee for this state', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='state',
            field=models.CharField(choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('fct', 'Federal Capital Territory (Abuja)'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara')], default=1, help_text='State this fee applies to', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='deliveryzone',
            index=models.Index(fields=['state'], name='delivery_de_state_f4f70e_idx'),
        ),
        migrations.DeleteModel(
            name='DeliveryPricingRule',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='base_fee',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='code',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='description',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='estimated_delivery_days',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='free_delivery_threshold',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='rush_delivery_available',
        ),
        migrations.RemoveField(
            model_name='deliveryzone',
            name='rush_delivery_premium',
        ),
    ]
