# Generated by Django 6.0.6 on 2026-07-21 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, help_text='Unique payment reference (UUID)', max_length=255, unique=True)),
                ('paystack_transaction_id', models.CharField(blank=True, db_index=True, help_text='Paystack transaction ID from verification response', max_length=100)),
                ('paystack_access_code', models.CharField(blank=True, help_text='Paystack access code from payment initialization', max_length=255)),
                ('email', models.EmailField(help_text='Customer email at time of payment', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in the transaction', max_digits=10)),
                ('currency', models.CharField(default='NGN', help_text='Currency used for the transaction', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current transaction status', max_length=20)),
                ('gateway_response', models.JSONField(blank=True, default=dict, help_text='Complete Paystack API response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(blank=True, help_text='Cart this payment was initiated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cart.cart')),
                ('order', models.ForeignKey(blank=True, help_text='Order linked to this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (null for guest checkout)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='payment_tra_referen_2a6f6d_idx'), models.Index(fields=['status'], name='payment_tra_status_373de7_idx'), models.Index(fields=['paystack_transaction_id'], name='payment_tra_paystac_b61031_idx'), models.Index(fields=['user', '-created_at'], name='payment_tra_user_id_01aff8_idx')],
            },
        ),
    ]
