# Generated by Django 6.0.2 on 2026-03-01 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_base_price'),
        ('orders', '0002_remove_order_payment_transaction_id_and_more'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='cart',
            field=models.ForeignKey(blank=True, help_text='Cart this payment was initiated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='NGN', help_text='Currency used for the transaction', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='flutterwave_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Flutterwave transaction ID from verification response', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user (null for guest checkout)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid in the transaction', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(help_text='Customer email at time of payment', max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order linked to this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(db_index=True, help_text='Unique payment reference (UUID)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Current transaction status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference'], name='payment_tra_referen_2a6f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='payment_tra_status_373de7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='payment_tra_user_id_01aff8_idx'),
        ),
    ]
