# Generated by Django 6.0.2 on 2026-06-14 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitemaddon'),
        ('orders', '0002_remove_order_payment_transaction_id_and_more'),
        ('payment', '0002_alter_transaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='flutterwave_transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='gateway_response',
            field=models.JSONField(blank=True, default=dict, help_text='Complete Paystack API response'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_access_code',
            field=models.CharField(blank=True, help_text='Paystack access code from payment initialization', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paystack_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Paystack transaction ID from verification response', max_length=100),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['paystack_transaction_id'], name='payment_tra_paystac_b61031_idx'),
        ),
    ]
