# Generated by Django 6.0.2 on 2026-02-18 00:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeCustomizationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_type', models.CharField(choices=[('topper', 'Cake Topper'), ('candle', 'Candle'), ('birthday_card', 'Birthday Card'), ('chocolate', 'Chocolate Box'), ('wine', 'Wine Bottle'), ('whiskey', 'Whiskey Bottle (200ml)')], max_length=50, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per single unit of this customization', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.CharField(blank=True, help_text="e.g., 'Premium gold cake topper', 'Scented vanilla candle'", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Disable to hide from customer selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cake Customization Option',
                'verbose_name_plural': 'Cake Customization Options',
                'ordering': ['customization_type'],
            },
        ),
        migrations.CreateModel(
            name='CakeFlavorPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(choices=[('Vanilla', 'Vanilla'), ('Chocolate', 'Chocolate'), ('Coconut', 'Coconut'), ('Marble', 'Marble'), ('Fruit cake', 'Fruit Cake')], max_length=50, unique=True)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplier applied to base price. E.g., 1.2 = 20% more expensive', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.50'))])),
                ('is_active', models.BooleanField(default=True, help_text='Disable to hide this flavor from customer selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cake Flavor Price',
                'verbose_name_plural': 'Cake Flavor Prices',
                'ordering': ['flavor'],
            },
        ),
        migrations.CreateModel(
            name='CakeSizeMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('6', '6 Inches'), ('8', '8 Inches'), ('10', '10 Inches'), ('12', '12 Inches'), ('14', '14 Inches')], max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text="Multiplier applied to product's design price. E.g., 1.5 = 50% more expensive", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cake Size Multiplier',
                'verbose_name_plural': 'Cake Size Multipliers',
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('flavour_1', models.CharField(blank=True, help_text='First flavor selection', max_length=50)),
                ('flavour_2', models.CharField(blank=True, help_text='Second flavor selection (optional)', max_length=50)),
                ('size', models.CharField(blank=True, help_text="Selected cake size (e.g., '6', '8', '10')", max_length=20)),
                ('colours', models.CharField(blank=True, help_text="Max 2 colours, e.g., 'Blue and white'", max_length=100)),
                ('cake_topper', models.PositiveIntegerField(default=0, help_text='Number of cake toppers', validators=[django.core.validators.MinValueValidator(0)])),
                ('candle', models.PositiveIntegerField(default=0, help_text='Number of candles', validators=[django.core.validators.MinValueValidator(0)])),
                ('birthday_card', models.PositiveIntegerField(default=0, help_text='Number of birthday cards', validators=[django.core.validators.MinValueValidator(0)])),
                ('chocolate', models.PositiveIntegerField(default=0, help_text='Number of chocolate boxes', validators=[django.core.validators.MinValueValidator(0)])),
                ('wine', models.PositiveIntegerField(default=0, help_text='Number of wine bottles', validators=[django.core.validators.MinValueValidator(0)])),
                ('whiskey_200ml', models.PositiveIntegerField(default=0, help_text='Number of whiskey bottles (200ml)', validators=[django.core.validators.MinValueValidator(0)])),
                ('additional_notes', models.TextField(blank=True, max_length=1000)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Snapshot of product.price at time of addition (design base price for cakes)', max_digits=10)),
                ('customization_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost of customizations for ONE cake (add-ons only)', max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time_slot', models.CharField(blank=True, max_length=50)),
                ('calculated_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='cart.cart')),
            ],
            options={
                'verbose_name': 'Delivery Information',
                'verbose_name_plural': 'Delivery Information',
            },
        ),
    ]
