# Generated by Django 6.0.2 on 2026-02-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of product.price at time of addition (design base price for cakes)', max_digits=10, null=True),
        ),
    ]
