# Generated by Django 6.0.6 on 2026-07-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryinfo',
            name='state',
        ),
        migrations.RemoveField(
            model_name='saveddeliveryinfo',
            name='state',
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='area_name',
            field=models.CharField(blank=True, help_text='Delivery zone area name — matched against active DeliveryZone entries for fee calculation', max_length=100),
        ),
        migrations.AddField(
            model_name='saveddeliveryinfo',
            name='area_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
