# Generated by Django 6.0.2 on 2026-05-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_unique_together_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cakecustomizationoption',
            options={'ordering': ['name'], 'verbose_name': 'Cake Customization Option', 'verbose_name_plural': 'Cake Customization Options'},
        ),
        migrations.AddField(
            model_name='cakecustomizationoption',
            name='name',
            field=models.CharField(default=1, help_text="Display name e.g. 'Balloon Pack', 'Cake Topper'", max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cakecustomizationoption',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated unique identifier', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cakecustomizationoption',
            name='customization_type',
            field=models.CharField(blank=True, help_text='Leave blank for custom addons created by admin', max_length=50),
        ),
    ]
