# Generated by Django 6.0.2 on 2026-05-31 22:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cakecustomizationoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(help_text='The selected customization option', on_delete=django.db.models.deletion.PROTECT, to='cart.cakecustomizationoption')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_addons', to='cart.cartitem')),
            ],
            options={
                'verbose_name': 'Cart Item Addon',
                'verbose_name_plural': 'Cart Item Addons',
                'ordering': ['added_at'],
                'unique_together': {('cart_item', 'addon')},
            },
        ),
    ]
