# Generated by Django 6.0.2 on 2026-02-14 07:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '__first__'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, help_text='Unique order identifier (ORD-YYYYMMDD-UUID8)', max_length=50, unique=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Email for guest checkout', max_length=254)),
                ('guest_phone', models.CharField(blank=True, help_text='Phone for guest checkout', max_length=20)),
                ('customer_name', models.CharField(help_text='Full name for order/delivery', max_length=100)),
                ('customer_email', models.EmailField(help_text='Email for order confirmation and updates', max_length=254)),
                ('customer_phone', models.CharField(help_text='Phone number for order updates', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal from cart (items only)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Delivery fee calculated at checkout', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Final total to be paid (subtotal + delivery_fee)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready for Pickup/Delivery'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current order status', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', help_text='Payment status', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash on Delivery')], help_text='How customer will pay', max_length=20)),
                ('payment_transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, help_text='When payment was received', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When order was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When order was confirmed', null=True)),
                ('processing_at', models.DateTimeField(blank=True, help_text='When order started processing', null=True)),
                ('ready_at', models.DateTimeField(blank=True, help_text='When order was marked ready', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When order was completed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When order was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for staff')),
                ('cart', models.ForeignKey(blank=True, help_text='Original cart (for reference, cart becomes inactive after order)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cart')),
                ('user', models.ForeignKey(blank=True, help_text='Customer user account (null for guest)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='Full delivery address')),
                ('city', models.CharField(help_text='City/Area for delivery zone calculation', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('delivery_date', models.DateField(help_text='Requested delivery date')),
                ('delivery_time_slot', models.CharField(blank=True, help_text="Preferred time slot (e.g., '10am-12pm')", max_length=50)),
                ('delivery_zone', models.CharField(blank=True, help_text='Delivery zone used for fee calculation', max_length=50)),
                ('delivery_fee', models.DecimalField(decimal_places=2, help_text='Delivery fee charged', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for delivery', max_length=1000)),
                ('is_delivered', models.BooleanField(default=False, help_text='Whether delivery has been completed')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When delivery was completed', null=True)),
                ('delivery_notes', models.TextField(blank=True, help_text='Notes from delivery person')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='Related order', on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Delivery',
                'verbose_name_plural': 'Order Deliveries',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Order Created'), ('confirmed', 'Order Confirmed'), ('payment_received', 'Payment Received'), ('processing', 'Processing Started'), ('ready', 'Ready for Pickup/Delivery'), ('delivered', 'Delivered'), ('completed', 'Order Completed'), ('cancelled', 'Order Cancelled'), ('refunded', 'Refunded'), ('note_added', 'Note Added'), ('status_changed', 'Status Changed')], help_text='Action taken', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Details about the action')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When action occurred')),
                ('old_value', models.CharField(blank=True, help_text='Previous value (for status changes)', max_length=100)),
                ('new_value', models.CharField(blank=True, help_text='New value (for status changes)', max_length=100)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Staff member who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_actions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Related order', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of cakes', validators=[django.core.validators.MinValueValidator(1)])),
                ('flavour_1', models.CharField(blank=True, help_text='First flavor chosen', max_length=50)),
                ('flavour_2', models.CharField(blank=True, help_text='Second flavor chosen', max_length=50)),
                ('size', models.CharField(blank=True, help_text='Cake size (e.g., 6, 8, 10, 12, 14 inches)', max_length=20)),
                ('colours', models.CharField(blank=True, help_text='Colors/decorations', max_length=100)),
                ('cake_topper', models.PositiveIntegerField(default=0, help_text='Number of toppers', validators=[django.core.validators.MinValueValidator(0)])),
                ('candle', models.PositiveIntegerField(default=0, help_text='Number of candles', validators=[django.core.validators.MinValueValidator(0)])),
                ('birthday_card', models.PositiveIntegerField(default=0, help_text='Number of cards', validators=[django.core.validators.MinValueValidator(0)])),
                ('chocolate', models.PositiveIntegerField(default=0, help_text='Number of chocolate boxes', validators=[django.core.validators.MinValueValidator(0)])),
                ('wine', models.PositiveIntegerField(default=0, help_text='Number of wine bottles', validators=[django.core.validators.MinValueValidator(0)])),
                ('whiskey_200ml', models.PositiveIntegerField(default=0, help_text='Number of whiskey bottles', validators=[django.core.validators.MinValueValidator(0)])),
                ('additional_notes', models.TextField(blank=True, help_text='Special instructions for this item', max_length=1000)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per cake (product.price snapshot)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('customization_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost of customizations per cake', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per cake (base + customizations)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('item_total', models.DecimalField(decimal_places=2, help_text='Total for this line item (unit_price × quantity)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When item was added to order')),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(help_text='Product ordered', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash on Delivery')], help_text='Payment method used', max_length=20)),
                ('transaction_id', models.CharField(db_index=True, help_text='Payment gateway transaction ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank/Payment reference', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Payment notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When payment was initiated')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When payment was processed', null=True)),
                ('order', models.ForeignKey(help_text='Related order', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='orders_orde_payment_bc131d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['order', '-timestamp'], name='orders_orde_order_i_db9f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='orders_orde_order_i_52f79a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['transaction_id'], name='orders_orde_transac_ea1414_idx'),
        ),
        migrations.AddIndex(
            model_name='orderpayment',
            index=models.Index(fields=['order', '-created_at'], name='orders_orde_order_i_6dc0e2_idx'),
        ),
    ]
