# Generated by Django 6.0.2 on 2026-02-18 21:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_base_price'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='flutterwave_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Flutterwave payment reference', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='flutterwave_response',
            field=models.JSONField(blank=True, help_text='Full Flutterwave response for reference', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='flutterwave_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Flutterwave transaction ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='flutterwave', editable=False, help_text='Payment method (always Flutterwave)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['flutterwave_transaction_id'], name='orders_orde_flutter_9b43b0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['flutterwave_reference'], name='orders_orde_flutter_2810c2_idx'),
        ),
    ]
