# Generated by Django 6.0.2 on 2026-06-14 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitemaddon'),
        ('orders', '0002_remove_order_payment_transaction_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_flutter_9b43b0_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_flutter_2810c2_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Paystack payment reference', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_response',
            field=models.JSONField(blank=True, help_text='Full Paystack response for reference', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paystack_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text='Paystack transaction ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='paystack', editable=False, help_text='Payment method (always Paystack)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paystack_transaction_id'], name='orders_orde_paystac_c0543b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['paystack_reference'], name='orders_orde_paystac_c04c19_idx'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='flutterwave_reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flutterwave_response',
        ),
        migrations.RemoveField(
            model_name='order',
            name='flutterwave_transaction_id',
        ),
    ]
