# Generated by Django 6.0.6 on 2026-06-27 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_orders_orde_flutter_9b43b0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='additional_notes',
            field=models.TextField(blank=True, help_text='Special instructions for this item', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='birthday_card',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of cards', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cake_topper',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of toppers', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='candle',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of candles', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='chocolate',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of chocolate boxes', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='colours',
            field=models.CharField(blank=True, help_text='Colors/decorations', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='flavour_1',
            field=models.CharField(blank=True, help_text='First flavor chosen', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='flavour_2',
            field=models.CharField(blank=True, help_text='Second flavor chosen', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, help_text='Cake size (e.g., 6, 8, 10, 12, 14 inches)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='whiskey_200ml',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of whiskey bottles', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wine',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of wine bottles', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
