# Generated by Django 6.0.6 on 2026-07-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliveryzone_order_fulfillment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(help_text='Requested pickup date')),
                ('pickup_time_slot', models.CharField(blank=True, help_text="Preferred time slot (e.g., '10am-12pm')", max_length=50)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for pickup', max_length=1000)),
                ('is_picked_up', models.BooleanField(default=False, help_text='Whether pickup has been completed')),
                ('picked_up_at', models.DateTimeField(blank=True, help_text='When pickup was completed', null=True)),
                ('pickup_notes', models.TextField(blank=True, help_text='Notes from staff at pickup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='Related order', on_delete=django.db.models.deletion.CASCADE, related_name='pickup', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Pickup',
                'verbose_name_plural': 'Order Pickups',
            },
        ),
        migrations.DeleteModel(
            name='DeliveryZone',
        ),
    ]
