# Generated by Django 6.0.2 on 2026-02-14 07:54

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category (e.g., Birthday, Wedding).', max_length=200)),
                ('slug', models.SlugField(help_text='A URL-friendly identifier for the category.', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='products_ca_name_693421_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('cake', 'Cake'), ('pastry', 'Pastry')], default='cake', help_text='Cake: customizable, made-to-order. Pastry: fixed product.', max_length=20)),
                ('name', models.CharField(help_text="The name of the product (e.g., 'Butterfly Cake', 'Chocolate Croissant').", max_length=200)),
                ('slug', models.SlugField(help_text='A URL-friendly identifier for the product.', max_length=200)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='An image of the product. Recommended size: 800x600px.', max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField(blank=True, help_text='A detailed description of the product.', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='For cakes: Design base fee. For pastries: Fixed selling price.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('layers', models.PositiveIntegerField(blank=True, default=2, help_text='Number of cake layers (e.g., 2, 4). Required for cakes.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('covering', models.CharField(blank=True, choices=[('buttercream', 'Buttercream'), ('fondant', 'Fondant'), ('cream_cheese', 'Cream Cheese Frosting'), ('whipped_cream', 'Whipped Cream'), ('naked', 'Naked Cake'), ('ganache', 'Chocolate Ganache')], help_text='Type of cake covering. Required for cakes.', max_length=50, null=True)),
                ('inspiration', models.TextField(blank=True, help_text='Design inspiration or story behind the cake (optional).', null=True)),
                ('preparation_days', models.PositiveIntegerField(blank=True, default=3, help_text='Minimum days needed to prepare this product. Required for cakes.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('available', models.BooleanField(default=True, help_text='Whether the product is available for purchase. Uncheck to hide from store.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category for organizing products (e.g., Birthday, Wedding).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'slug'], name='products_pr_id_a08e3c_idx'), models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'), models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'), models.Index(fields=['available'], name='products_pr_availab_21d9ca_idx'), models.Index(fields=['product_type', 'available'], name='products_pr_product_9a031c_idx'), models.Index(fields=['category', 'available'], name='products_pr_categor_d726ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'slug'), name='unique_product_slug_per_category')],
            },
        ),
    ]
