# Generated by Django 6.0.2 on 2026-02-16 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='layers',
            field=models.PositiveIntegerField(blank=True, help_text='Number of cake layers (e.g., 2, 4). Required for cakes.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
