# Generated by Django 6.0.2 on 2026-06-02 11:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Short description of this category.', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Category image. Recommended size: 800x600px.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
