# Generated by Django 6.0.2 on 2026-02-17 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_layers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preparation_days',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum days needed to prepare this product. Required for cakes.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
