# Generated by Django 5.1.4 on 2025-09-19 03:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='An image of the product.', max_length=255, null=True, verbose_name='image'),
        ),
    ]
